package TratamentoExecaoNelio;

public class Finally {

	public static void main(String[] args) {
		// TODO Auto-generated method stub

		/*As vezes é necessário executar um código mesmo que tenha havido uma Exception. 
		 * É para isto que servem os blocos finally
		 * 
		 * Os comandos dentro de um bloco finally serão executados de qualquer maneira, mesmo que a execução 
		 * tenha passado por um bloco catch.
			Ao contrário dos blocos catch você só pode ter um bloco finally por cada bloco try.
		 */
	}

}
